### ISSUE TITLE
Missing Styleseet

### ISSUE THREAD

**Issue by kenhowardpdx** [AWiderDotNET/AWiderDotNet.github.io#7]
![image](https://cloud.githubusercontent.com/assets/1892667/26793430/d2724796-49d2-11e7-9098-42bd0ce95264.png)

![image](https://cloud.githubusercontent.com/assets/1892667/26793464/f384f30c-49d2-11e7-95c3-031e40c2e956.png)

**Comment by RyKilleen** [comment]
Looks like it was a delay in Jekyll's Sass compilation, styles are now loading.

**Comment by SeanKilleen** [comment]
👍 yep, looks like things are good now -- just took GitHub Pages a second to catch up. Going to close this out. 

Thanks for reporting it! Looking forward to seeing issues logged for where you'd like this to go, and PRs to fix it up more.
